AWSTemplateFormatVersion: "2010-09-09"
Description:
Resources:
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: ECS
    TwentyFivePercentAtATime:

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentConfig
    Properties:
      MinimumHealthyHosts:
      Type: "FLEET_PERCENT"
      Value: 75

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentConfigName: CodeDeployDefault.ECSCanary10percent5Minutes
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      ServiceRoleArn: arn:aws:iam::765154140259:role/CodeDeployRoleForECS
